[tool.poetry]
name = "pyinaturalist-export"
version = "0.0.1"
description = "Pyinaturalist extensions to convert iNaturalist observation data to and from multiple formats "
authors = ["Jordan Cook <Jordan.Cook@pioneer.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/JWCook/pyinaturalist-export"
repository = "https://github.com/JWCook/pyinaturalist-export"
documentation = "https://pyinaturalist.readthedocs.io"
keywords = ["inaturalist", "biodiversity", "export", "convert", "csv", "darwin-core"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Typing :: Typed",
]
include = [
    { path = "*.md" },
    { path = "*.yml" },
    { path = "docs", format = "sdist" },
    { path = "examples", format = "sdist" },
    { path = "test", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.8"
pyinaturalist = "0.13.0.dev289"
flatten-dict = {version = "^0.4.0", optional = true}
tablib = {version = "^3.0.0", optional = true}
tabulate = {version = "^0.8.9", optional = true}

# Optional tools
openpyxl = {version = ">=2.6.0", optional = true}
pandas = {version = ">=1.2", optional = true}
pyarrow = {version = ">=4.0.0", optional = true}
xmltodict = {version = ">=0.12.0", optional = true}

[tool.poetry.extras]
all = ["pandas", "pyarrow", "tablib[all]", "xmltodict"]
dwc = ["xmltodict"]
parquet = ["pandas", "pyarrow"]
xlsx = ["flatten-dict", "tablib", "openpyxl"]

[tool.poetry.dev-dependencies]
black = "21.5b0"
isort = ">=5.8"
flake8 = "^3.9"
mypy = "^0.812"
pytest = "^6.2"
pytest-cov = ">=2.11"
pytest-xdist = ">=2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
line-length = 100

[tool.coverage.html]
directory = 'test-reports'

[tool.coverage.run]
branch = true
source = ['pyinaturalist_export']

[tool.isort]
profile = 'black'
line_length = 100
skip_gitignore = true
skip = ['pyinaturalist_export/__init__.py']
known_first_party = ['test']
# Things that are common enough they may as well be grouped with stdlib imports
extra_standard_library = ['dateutil', 'pytest', 'setuptools']
